# Generated by Django 4.1.1 on 2022-10-21 07:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400, null=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255, null=True)),
                ('pincode', models.CharField(max_length=6, null=True)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(default=101)),
                ('room_type', models.CharField(choices=[('Luxury', 'Luxury'), ('Normal', 'Normal'), ('Economic', 'Economic')], max_length=200)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('is_available', models.BooleanField(default=3)),
                ('hotel_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservapp.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('checkin_date', models.DateTimeField(default=datetime.datetime.now)),
                ('checkout_date', models.DateTimeField(default=datetime.datetime(2022, 10, 22, 12, 32, 46, 254982))),
                ('check_out', models.BooleanField(default=False)),
                ('no_of_guests', models.IntegerField(default=1)),
                ('phone_number', models.CharField(max_length=14, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservapp.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservapp.room')),
            ],
        ),
    ]
