# Generated by Django 4.1.1 on 2022-10-21 07:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateTimeField(default=datetime.datetime(2022, 10, 21, 12, 47, 7, 485071))),
                ('checkout_date', models.DateTimeField(default=datetime.datetime(2022, 10, 22, 12, 47, 7, 485071))),
                ('check_out', models.BooleanField(default=False)),
                ('no_of_guests', models.IntegerField(default=1)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservapp.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservapp.room')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
