# Generated by Django 4.1.1 on 2022-10-21 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservapp', '0002_bookings_delete_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='checkin_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 21, 13, 1, 25, 362699)),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='checkout_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 22, 13, 1, 25, 362699)),
        ),
    ]
