# Generated by Django 4.1.1 on 2022-10-21 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservapp', '0003_alter_bookings_checkin_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
