# Generated by Django 4.1.1 on 2022-10-21 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservapp', '0005_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 21, 13, 12, 20, 385255)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 22, 13, 12, 20, 385255)),
        ),
    ]
