# Generated by Django 4.1.1 on 2022-10-21 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservapp', '0006_alter_booking_checkin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 21, 13, 14, 58, 890147)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 22, 13, 14, 58, 890147)),
        ),
    ]
