# Generated by Django 4.1.1 on 2022-10-25 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservapp', '0007_alter_booking_checkin_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 9, 9, 4, 461525)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 9, 9, 4, 461525)),
        ),
    ]
