# Generated by Django 4.1.1 on 2022-10-25 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservapp', '0008_hotel_description_alter_booking_checkin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 9, 17, 30, 728903)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 9, 17, 30, 728903)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
