# Generated by Django 4.1.1 on 2022-10-25 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservapp', '0011_alter_booking_checkin_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='phone',
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 17, 31, 28, 725383)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 17, 31, 28, 725383)),
        ),
    ]
