# Generated by Django 4.1.1 on 2022-10-25 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservapp', '0012_remove_hotel_phone_alter_booking_checkin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 19, 27, 56, 571061)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 19, 27, 56, 572058)),
        ),
    ]
